apiVersion: apps/v1
kind: Deployment
metadata:
  name: listing-service
  namespace: replate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listing-service
  template:
    metadata:
      labels:
        app: listing-service
    spec:
      containers:
        - name: listing-service
          image: norbinorbert/replate-listing-service:1.0.0
          ports:
              - containerPort: 8082
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: replate-config
                  key: mysql-host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: replate-config
                  key: mysql-port
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: replate-secrets
                  key: mysql-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: replate-secrets
                  key: mysql-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: replate-secrets
                  key: jwt-secret
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: replate-config
                  key: auth-service-url
            - name: FILTER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: replate-config
                  key: filter-service-url
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: replate-config
                  key: spring-profiles-active
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
      volumes:
        - name: uploads
          emptyDir: { }

---
apiVersion: v1
kind: Service
metadata:
  name: listing-service
  namespace: replate
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: listing-service

