apiVersion: v1
kind: Secret
metadata:
  name: replate-secrets
  namespace: replate
type: Opaque
stringData:
  mysql-root-password: root
  mysql-user: root
  mysql-password: root
  jwt-secret: hSwUZ327v3OdcW9vwkgLcgkXUI0ofVlliMQvZomqaeQ
