apiVersion: v1
kind: Secret
metadata:
  name: replate-secrets
  namespace: replate
type: Opaque
data:
  mysql-root-password: cm9vdA==
  mysql-user: cm9vdA==
  mysql-password: cm9vdA==
  jwt-secret: aFN3VVozMjd2M09kY1c5dndrZ0xjZ2tYVUkwb2ZWbGxpTVF2Wm9tcWFlUQ==
