spring.config.activate.on-profile=create
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:sql/insert_categories.sql, classpath:sql/insert_countries.sql, \
  classpath:sql/insert_counties.sql, classpath:sql/insert_cities.sql

